version: '3.3'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
    - "27017:27107"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_DATABASE: customer-service
    volumes:
      - ./data:/data/db